### ISSUE TITLE
Translate options menu

### ISSUE THREAD

**Issue by Tolrin** [Lazlocke/wizardsc#10]
Several images need translating for the options menu.

![Options Menu](https://user-images.githubusercontent.com/58127820/76155795-4e7c2400-60bf-11ea-8932-af51a0de2a35.jpg)

The images are:
opt_a00 - 03
opt_c00 - 01
opt_h00 - 02

**Comment by Lazlocke** [comment]
opt_a00 (left side, top to bottom)
Screen Resolution
Text Speed (Fast <-> Slow)
Graphic Speed (????) 
Window Transparency  (Clear <-> Opaque)
Tooltip Popup Setting
Right Click Option

(Right side)
BGM Volume
SFX Volume
Voice Volume

opt_a01
Back to Game

opt_a02
Back to Title

opt_a03
Exit Game

opt_c00
Fast (????)

opt_c01
Clean (???? Instant? Are these for graphics transitions maybe? Quick fade vs instant?)

opt_h00
Fast

opt_h01
Normal

opt_h02
Slow

**Comment by Lazlocke** [comment]
It looks like the buttons themselves need to be translated still?
@Tolrin

**Comment by Tolrin** [comment]
Options menu is complete now, arguably some of the already English buttons could be re-done to have a consistent font, but that can be revisited later if someone feels energetic.
