### ISSUE TITLE
Translate equip menu

### ISSUE THREAD

**Issue by Tolrin** [Lazlocke/wizardsc#11]
The equip menu needs translation.

![Equip Menu](https://user-images.githubusercontent.com/58127820/76156054-b8e29380-60c2-11ea-89ec-eb569cf93ca0.jpg)

Images that appear to need translation are:
shkn_a00 - 03
shkn_b00
shkn_c00 - 01
shkn_d00 - 02
shkn_e00 - 04
shkn_f00
shkn_g00

**Comment by Lazlocke** [comment]
shkn_a00 - 03
買う - Buy
売る - Sell
装備品 - Equipment
その他 - Miscellaneous

shkn_b00
捨てるアイテムを選択してください - Select an Item to discard

shkn_c00 - 01
装備品 - Equipment
その他 - Miscellaneous

shkn_d00 
品目 - Item
種類 - Category/Type
商品名 - Name/Product
値段 - Price (B)
詳細 - Details

shkn_d01 (top to bottom)
買 - Buy
売 - Sell
装 - Equip (Weapon?)
装 - Wear (Accessory? Clothes? Armor?) 
持 - Possessed/On Hand (?)
捨 - Discard

shkn_d02
確認 - Confirm

shkn_e00
所持金 - Cash on Hand
購入金額 - Purchase Amount
売却金額 - Sale Amount
計 - Total/End Result

shkn_e01
アイテム数 - Quantity (Item Count)

shkn_e02
決定 - Confirm

shkn_g04
選択解除 - Deselect

shkn_f00
現在装備 - Current Equipment

shkn_g_00
品目 - Item
種類 - Category/Type
名前 - Name
価値 - Value
