### ISSUE TITLE
Translate Combat Interface

### ISSUE THREAD

**Issue by Lazlocke** [Lazlocke/wizardsc#12]

**Comment by Lazlocke** [comment]
![Untitled](https://user-images.githubusercontent.com/52725030/80764786-460bfc80-8af6-11ea-9ab9-3a5a5d6669da.png)

**Comment by Lazlocke** [comment]
格闘/武器の使用頻度 - Physical Attack (Frequency to use Weapon/Grapple attacks)
自由 - No Priority
積極的 - Prioritize 
消極的 - Rare
禁止 - Never

攻撃魔法の使用頻度 - Attack Magic

守備魔法の使用頻度 - Defense Magic

ターゲッティング - Targeting
自由 - Any
近い敵 - Nearby
遠い敵 - Distant
体力小 - Weak
体力大 - Strong

敵との距離 - Positioning (Distance From Enemy)
自由 - Any
接近戦重視 - Hand to Hand
近距離戦重視 - Short Range
中距離戦重視 - Mid Range
遠距離戦重視 - Long Range

奥義指定のスキル - Secret Skills
開放 - Free
封印 - Sealed

体力維持 - Health Importance (What HP % to retreat at)
無視 - Never
一割 - 10%
二割 - 20%
三割 - 30%
四割 - 40%
五割 - 50%
六割 - 60%
七割 - 70%
退却 - Retreat!

戦闘速度 - Combat Speed
普通 - Slow
中速 - Medium
高速 - Fast

体カバー - Body Cover (???)

**Comment by Lazlocke** [comment]
Images are chip/din* and most of dun*

**Comment by Tolrin** [comment]
Some buttons and images in the bottom right corner of the combat screen need translating:
![ss (2020-06-25 at 05 11 43)](https://user-images.githubusercontent.com/58127820/85795979-27e20780-b707-11ea-8f97-3c49b503d061.jpg)
![ss (2020-06-25 at 05 12 09)](https://user-images.githubusercontent.com/58127820/85795983-29abcb00-b707-11ea-9848-024079a48d0c.jpg)

**Comment by Lazlocke** [comment]
I believe everything is translated on these now except the floor/round indicators in the upper left? 
@Tolrin 
Can you confirm that? Once that's done, this can be closed.

**Comment by Tolrin** [comment]
Images are now complete for this except dun_a01.
