### ISSUE TITLE
Extra Menus

### ISSUE THREAD

**Issue by Tolrin** [Lazlocke/wizardsc#13]
The Extra Menus need translation too!

New game plus screens:
1
![ss (2020-07-15 at 06 24 03)](https://user-images.githubusercontent.com/58127820/87606243-79f3c880-c6c8-11ea-86cb-b658a9cf7ffe.jpg)
2
![ss (2020-07-15 at 06 24 34)](https://user-images.githubusercontent.com/58127820/87606254-81b36d00-c6c8-11ea-9e5e-147afecd534d.jpg)

Extra menus:
Main:
![ss (2020-07-15 at 05 12 54)](https://user-images.githubusercontent.com/58127820/87596901-e5389d00-c6be-11ea-9e94-84820f6fdc19.jpg)
1
![ss (2020-07-15 at 05 16 29)](https://user-images.githubusercontent.com/58127820/87596937-f1245f00-c6be-11ea-9c0e-2669e7e0eac5.jpg)
2
![ss (2020-07-15 at 06 26 30)](https://user-images.githubusercontent.com/58127820/87606331-b8898300-c6c8-11ea-82e3-412efa846cd7.jpg)
3
![ss (2020-07-15 at 06 27 31)](https://user-images.githubusercontent.com/58127820/87606407-e8d12180-c6c8-11ea-9866-4375f383e205.jpg)
4
![ss (2020-07-15 at 06 28 24)](https://user-images.githubusercontent.com/58127820/87606440-f9819780-c6c8-11ea-9c24-a5480072db76.jpg)
5a
![ss (2020-07-15 at 06 29 49)](https://user-images.githubusercontent.com/58127820/87606526-3057ad80-c6c9-11ea-9a64-854b360f091f.jpg)
5b
![ss (2020-07-15 at 06 30 17)](https://user-images.githubusercontent.com/58127820/87606544-3e0d3300-c6c9-11ea-9a39-b09d84074d5b.jpg)

**Comment by Lazlocke** [comment]
1.) 
セリス登録画面 - Celes Registration (Record?) Screen
戻る - Back
指示確認 - Check Orders

2.)
体力 - HP
魔力 - MP
優先指定スキル - Preferred Skills
必殺指定スキル - Special Skills
(Below should match combat interface)
格闘/武器の使用頻度 - Phys Attacks
攻撃魔法の使用頻度 - Attack Magic
守備魔法の使用頻度 - Defense Magic
ターゲッティング - Targeting
敵との距離 - Positioning
奥義指定のスキル - Secret Skills
体力維持 - HP Retreat Thingy
(Buttons)
名称変更 - Change Name
スキル指示 - Skill Orders
戻る - Back
保存 - Save

Extra
(Clockwise)
おまけシナリオ - Extra Scenes
イベント回想 - Event Gallery
音楽鑑賞 - Music Gallery
CG鑑賞 - CG Gallery
Quiz - Quiz
英雄の塔に挑戦 - Tower of Heroes!
戻る - Back
助言 - Tips

1.)
おまけ - Extra
達成率 Collection Rate
戻る - Back

2.)
イベント回想 - Event Gallery

3.)
音楽鑑賞 - Music Gallery
(Music graphics done elsewhere)

4.)
CG鑑賞 - CG Gallery
CG達成率 - CG Collection Rate

5.)
英雄の塔に登る - Climb the Tower of Heroes
キャラクターをセット - Set Character

6.)
階 - Floor
指示確認 - Check Orders
削除 - Delete
戻る - Back
保存 - Save

**Comment by Tolrin** [comment]
Images are translated.
