### ISSUE TITLE
Images that Need Transparency Fixes

### ISSUE THREAD

**Issue by Lazlocke** [Lazlocke/wizardsc#20]

**Comment by Lazlocke** [comment]
![Untitled](https://user-images.githubusercontent.com/52725030/91680656-ca03de80-eb00-11ea-8652-1436b58bca29.png)

chip/skg_a22
chip/skg_a23

**Comment by Tolrin** [comment]
![ss (2020-11-11 at 10 26 01)](https://user-images.githubusercontent.com/58127820/98893888-823ef300-2471-11eb-8ab6-9bc0f06f8c4e.png)

chip/skl_b11

**Comment by esperknight** [comment]
Adding in original bmps of chip/skg_a22, chip/skg_a30 and chip/skl_b11 that has the original background color versus a transparent one.

**Comment by Lazlocke** [comment]
All are fixed. Metadata on skl_b11 was bad so I hex edited it to be not bad.
