### ISSUE TITLE
Translate the Main Room Interface

### ISSUE THREAD

**Issue by Lazlocke** [Lazlocke/wizardsc#6]
![main room interface](https://user-images.githubusercontent.com/52725030/60939926-7b590c80-a28e-11e9-8e58-eb4018cd4aad.png)

The images are located in chip.

Buttons on the left (ofc_b*.png) are:

戦闘訓練 - Exercise (lit. Combat Training, but includes all physical stuff)
魔法勉強 - Study Magic
アルバイト - Part Time Job
実践 - Adventure (lit. Execute/Implement)
模擬戦闘 - Sparring (lit. Mock Combat)
休憩 - Rest

The cutout in the top right is ofc_d00.png
師匠魔力 - Master's Mana (diff wording needed, but not sure what ATM)
体力 - Stamina (HP)
魔力 - Mana (MP)
年 - Year
月 - Month
週 - Week
状態 - Status
通常 - Normal (this is part of ofc_d04 among multiple others, can ignore for now)

**Comment by Tolrin** [comment]
Main interface work mostly complete, ofc_d00 could still use work on wording for Master's Mana and readability for Status.
