### ISSUE TITLE
Translate the Status Windows

### ISSUE THREAD

**Issue by Lazlocke** [Lazlocke/wizardsc#7]
![ofc_e00](https://user-images.githubusercontent.com/52725030/69979895-052aa000-14e4-11ea-8096-cb06ec2246bb.png)

ofc_e00 in chip

(Top right)
現在値 - Current Value (meh, leave blank maybe?)

肉体強化訓練 - Physical (lit Physical Strength Training)
格闘攻撃 - Unarmed (lit Grapple Attacking)
武器攻撃 - Armed (lit Weapon Attacking)
遠距離攻撃 - Ranged (lit Long Range Attacking) 
特殊武器攻撃 - Unconventional (lit Special Weapon Attacking)
魔法基礎訓練 - Wizardry (lit Magic Fundamentals Training)
火の魔法 - Fire Magic
水の魔法 - Water Magic
風の魔法 - Wind Magic
土の魔法 - Earth Magic
雷の魔法 - Lightning Magic
闇の魔法 - Dark Magic
光の魔法 - Light Magic
冒険者知識 - Adventuring (Adventure Studies)
一般知識 - General Studies
体力 - Health (HP is fine)
魔力 - Mana (MP is fine)
状態 - Status (should match Main interface)

**Comment by Lazlocke** [comment]
![ofc_f00](https://user-images.githubusercontent.com/52725030/69981509-512b1400-14e7-11ea-8771-38ebf8c6c170.png)

Should match the above except for top two and bottom one.

Top two
結果 - Result (double check context here, but I think this is the weekly results screen)
評価 - Value (double check context)

Bottom 
所持金の増減 - Money (Change in Money Possessed)

**Comment by Lazlocke** [comment]
![sta_a00](https://user-images.githubusercontent.com/52725030/69982947-73726100-14ea-11ea-81db-149541a93860.png)

sta_a00 in chip

The long list on the left is the same as above, except Health/Mana/Status are moved to the top. The fourth entry is:
師匠魔力 - Master's Mana  (should be consistent with other, but still not sure what)

Bottom five are:
武器 - Weapon

**Comment by Tolrin** [comment]
These images are now translated.
