### ISSUE TITLE
Translate various UI elements (buttons)

### ISSUE THREAD

**Issue by Tolrin** [Lazlocke/wizardsc#8]
Many buttons need translations.

Save/Load screens:
![Load Menu](https://user-images.githubusercontent.com/58127820/75934799-89762180-5e4b-11ea-8de8-bf9fc8cff5cb.jpg)

sav_a02.png through sav_a_05.png

Status sceen:
![status screen](https://user-images.githubusercontent.com/58127820/75935053-2df86380-5e4c-11ea-8e27-5797af25eea1.jpg)

sta_a01.png through sta_a04.png

Exercise screen:
![ofc](https://user-images.githubusercontent.com/58127820/75935144-76b01c80-5e4c-11ea-93db-9b148834770a.jpg)

ofc_e01.png and ofc_e02.png

Header text for various screens:
![ofc_e08](https://user-images.githubusercontent.com/58127820/75935552-7d8b5f00-5e4d-11ea-93c7-f71c48082921.png)

ofc_e08.png

**Comment by Lazlocke** [comment]
sav_a
読込 - Load
保存 - Save
削除 - Delete

sta_a
所持スキル確認 - Skills (Check Possessed Skills)
戻る - Back 
装備変更 - Equipment
スキル取得 - Train (Skill Acquisition)

ofc_e
決定 - Go! (Select)
戻る - Back

ofc_e8 (should match ofc_b)
戦闘訓練 - Exercise (Combat Training)
魔法勉強 - Study (Magic Study)
アルバイト - Job
実践 - Adventure
模擬戦闘 - Spar
休憩 - Rest

**Comment by Tolrin** [comment]
These images are now translated.
