### ISSUE TITLE
Translate acquire skills menu

### ISSUE THREAD

**Issue by Tolrin** [Lazlocke/wizardsc#9]
The skills menu mostly consists of images.

![aquire skills menu](https://user-images.githubusercontent.com/58127820/76154379-4fa25680-60a9-11ea-9617-466e87c7dab5.jpg)

skg_a00 is the top right menu.
skg_a01 - 02 are the large buttons bottom right

skg_a05 is the button on the far right of the scrolling section
skg_a20 is column 3... sure hope these are short words
skg_a21 is column 5, again not much text space
skg_a22 is column 6
skg_a34 is the second last column

skg_b00 - 03 is the column headers

skg_b04 - 06 are the buttons on the top

skg_c00 - 15 are the buttons in the top right window

**Comment by Lazlocke** [comment]
skg_a00
ステータス - Status
体力 - Stamina (HP)
魔力 - Mana (MP)
武器種類 - Weapon Type

skg_a01 - 02
選択解除 - Deselect
習得確定 - Learn (Confirm Acquire)

skg_a05 
確認 - Confirm

skg_a20 
肉体 - Body
格闘 - Grappling
武器 - Weapons 
遠武 - Ranged
特武 - Unconventional
魔基 - Magic
火魔 - Fire Magic
水魔 - Water Magic
風魔 - Wind Magic
土魔 - Earth Magic
雷魔 - Lightning Magic
闇魔 - Dark Magic
光魔 - Light Magic
冒険 - Adventure
一般 - General 

skg_a21
基本 - Basic
物理攻撃 - Physical Attack
魔法攻撃 - Magic Attack
召還物召還 - Summon Item (????????????)
補佐魔法 - Support Magic
治癒魔法 - Healing Magic
召喚魔法 - Summoning Magic

skg_a22 
These basically match skg_a20 above with the exception of the first and the last two.
無 - None
格 - Grappling
武 - Weapons 
遠 - Ranged
特 - Unconventional
火 - Fire
水 - Water
風 - Wind
土 - Earth
雷 - Lightning
闇 - Dark
光 - Light
回 - Heal
召 - Summon

skg_a34 is the second last column
なし - None
素手状態 - Barehanded
武器装備 - Weapon
棒装備 - Staff
斧装備 - Axe
ハンマー装備 - Hammer
手裏剣装備 - Throwing Knife
弓装備 - Bow
ナイフ装備 - Knife
ムチ装備 - Whip
樽装備 - Barrel

skg_b00
スキル名称 - Skill Name
種別 - Class
種類 - Type
属性 - Attribute
対象 - Target

skg_b01
効果対象 - Effect Area (??????)
持続 - Duration  
効果 - Effect

skg_b02
距離 - Range
範囲 - Area
威力 - Power
命中率 - Hit Rate

skg_b03
消費体力 - HP Needed
消費魔力 - MP Needed
必殺 - Critical 
制限 - Restriction (??)
説明 - Description

skg_b04 - 06 are the buttons on the top
詳細 - Details
**This shouldn't be translated as Details. They switch the info type being displayed, so should really be the category names, not just "Details 1" "Details 2" and "Details 3" 

skg_c00 - 15
These match skg_a20

**Comment by Tolrin** [comment]
![ss (2020-06-13 at 02 42 28)](https://user-images.githubusercontent.com/58127820/84576638-4e598780-ad84-11ea-8add-76ef9d2cda88.jpg)


Skill description UI also needs translating.

**Comment by Lazlocke** [comment]
名前 - Name
種類 - Type
種類 - School
種別 - Element
制限装備 - Weapon Required
消費体力 - HP Cost
必殺効果 - Can Crit
消費魔力 - MP Cost
スタン効果 - Can Stun
効果対象 - Target
バック効果 - Can Knockback
効果範囲 - Range
弾数 - Usage
威力 - Power
発動 - Cast Time
命中 - Accuracy
硬直 - Rigidity (Resistance to interruption?)
連携スキル - Related/Synergy Skill

**Comment by Tolrin** [comment]
Couple more skill menu UI bits left:

![skl_a00](https://user-images.githubusercontent.com/58127820/86522369-d0d8e280-be2a-11ea-8e90-05479f76604d.png)
![skl_b11](https://user-images.githubusercontent.com/58127820/86522376-e3531c00-be2a-11ea-86cc-780c747994e3.png)
![skl_b12](https://user-images.githubusercontent.com/58127820/86522370-d5050000-be2a-11ea-89dd-dda3cfd61fa8.png)

**Comment by Lazlocke** [comment]
skl_a00:
Skill Set
HP
MP
Status
Preferred Skills (should match below/elsewhere)
Secret Skills (should match below/elsewhere)

skl_b11
禁止 - Forbidden/Prohibited/Don't Use
許可 - Usable/Allowed
優先 - Preferred
奥義 - Secret
所持 - Owned (?? For passives maybe?)

skl_b12
Setting/Behavior

**Comment by Lazlocke** [comment]
I think all is translated here now? If not, re-open.
